trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: Use python 3.6
  inputs:
    versionSpec: '3.6'

- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install pytest pytest-cov
    # Add extra dependencies here:
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: PYTHONPATH=$(System.DefaultWorkingDirectory) pytest quaternions_acse --junitxml=junit/test-results.xml --cov=quaternions_acse --cov-report=xml --cov-report=html
  displayName: 'Run pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'junit/*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/htmlcov'
